version: '3'
services:
    books:
        build: ./src/
        volumes:
            - ./src/:/usr/src/app/
        ports:
            - 8000:8000
        environment:
            HOST: "0.0.0.0"
            PORT: 8000
            FLASK_DEBUG: 1